---
title: "Lin Li"
---

Tel: +86 151 1100 8192 | Email: lilin2024tuo@163.com

## Education

### Xi'an University of Architecture and Technology, Shaanxi, China
**Sep. 2019 – Jun. 2022**  
M.E. in Architecture, Concentrations in Building Technology Science, GPA 85.2/100

Related courses:
- Architecture and Urban Physical Environment
- Introduction to Human Settlement Environmental Science
- Green Architectural Technology Method
- Urban Outdoor Space Ecological Design Method

### Hunan University of Technology and Business, Hunan, China
**Sep. 2015 – Jun. 2019**  
B.Mgt. in Engineering Management, GPA 89.5/100 (3.48/4.0)

Related courses:
- Calculus
- Linear Algebra
- Theory of Probability and Statistics
- Architectural Mechanics
- Economics Theory

## Research Experience

### Xi'an University of Architecture and Technology, Shaanxi, China
**Sep. 2020 – Jun. 2022**  
Science and Technology Development Program funded by Shaanxi Provincial Construction Department (Z20190386) - Climate Zoning Researcher

- Formed the typical meteorological year documents of 30 major towns in Shaanxi Province
- Established the climate zoning of building energy saving design in 107 towns of Shaanxi Province
- Provided the design heating energy consumption index of new residential buildings in major towns
- Specified the thermal performance limits of different climate zones envelopes jointly by the team according to the 75% energy saving target
- Provided a dynamic calculation method for the trade-off judgment of the thermal performance of the envelope structure jointly by the team
- Formed a complete local energy-saving design standard jointly by the team

## Work Experience

### LONGi CENTER Renewable Energy Co., Ltd., Shaanxi, China
**Jul. 2022 – Present**  
Photovoltaic System Engineer, Intermediate Engineer

- Completed the preliminary scheme design of thirty distributed photovoltaic projects, among which eight projects won the bid
- Participated in the system and electrical construction drawing design of distributed photovoltaic projects in various scenarios such as rooftops, curtain walls, and carports, facilitating the successful grid connection of over 80MWp photovoltaic power stations

### Xi'an University of Architecture and Technology, Shaanxi, China
**Oct. 2019 – Mar. 2022**  
Green Building Evaluation and Identification Project - Project Leader

- Led and guided two juniors to complete the simulation analysis reports of the building physical environment, ecology and landscape and other indicators
- Resulted in six projects successfully obtaining the green building identification

## Publications

- Li Lin, Yan Zengfeng, Lang Jiachen, et al. Climatic Zoning of Design Standard for Energy Efficiency of Residential Buildings in Shaanxi (75%) [J]. Building Energy Efficiency (Chinese and English), 2023, 51(01):85-90.
- DB 61/T 5033-2022. Design Standard for Energy Efficiency of Residential Buildings [S]. Beijing: China Building Materials Industry Press, 2022.

## Extracurricular Activities

### The First National Green Building Design Competition in 2020, China
**Jun. 2020 – Aug. 2020**  
"Mountain + Hotel" Green Building Design Scheme - Team Member

- Analyzed the regional ventilation and indoor natural ventilation through CFD fluid dynamics simulation
- Explored the strategy of folding the wall, and formed a building space design scheme adapted to the four seasons climate jointly by the team
- Completed analysis diagrams and green performance demonstration materials jointly by the team

### Academic Conferences
**Jul. 2021, Aug. 2020**

- Member of Chinese Society of Building Physics
- 14th Building Physics Conference of China, Xiong'an, China
- The 16th International Conference on Green and Energy-efficient Building & New Technologies and Products Expo, Suzhou, China

## Additional Info and Awards

**Skills:** AutoCAD, SketchUp, ArcGIS, EnergyPlus, DesignBuilder, Phoenics, Airpak, Matlab, SPSS

**Awards:**
- China National Scholarship, 2016 – 2017
- Academic Scholarship × 6, 2015 – 2021
- Third Prize for Band C in 2017 National English Competition for College Students
